# docker-compose.yml
services:
  nginx:
    image: docker.guygubaby.top/nginx:stable-alpine
    container_name: notion-2api-nginx
    restart: always
    network_mode: host
    env_file:
      - .env
    environment:
      NGINX_PORT: ${NGINX_PORT:-4002}
      APP_PORT: ${APP_PORT:-4003}
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notion-2api-app
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      APP_PORT: ${APP_PORT:-4003}
    command: ["sh", "-c", "uvicorn main:app --host 127.0.0.1 --port ${APP_PORT:-4003} --workers 4"]
